curl -X POST http://localhost:3000/api/signup \
-H "Content-Type: application/json" \
-d '{
    "name": "test password",
    "email": "tester.password@app.co",
    "password": "12345678"
}'

### Sign In
curl -X POST http://localhost:3000/api/signin \
-H "Content-Type: application/json" \
-d '{
    "email": "tester.password@app.co",
    "password": "12345678"
}'