### Me
curl -X GET http://localhost:3000/api/me \
  --cookie "
    accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwODAyMDMxNDYzMzczMjA5NjEsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzQ5NzMwNTA3fQ.8nhLPoC_fyev1D5fAyB-_ZtdzwamFXhm4TCMfyKsn6g;
    refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTIzMTkzMjEsInJvbGUiOiJ1c2VyIiwidXNlcklkIjoxMDgwMjAzMTQ2MzM3MzIwOTYxfQ.cJ1dhgnTh5sIKkjPnUOSJyqVRXDXk8j-2IoQu4wiGb0;
    "


